name: Mobile Release

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build iOS IPA
        run: flutter build ipa --export-method ad-hoc --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: app-release-ipa
          path: build/ios/ipa

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            app-release-apk
            app-release-ipa
          token: ${{ secrets.GITHUB_TOKEN }}
